//! Procedural chemistry generation.
//!
//! The whole chemistry is a pure function of `(seed, ChemParams)`. Generation
//! runs in three stages:
//!
//! 1. **Primordials.** A fixed handful of small molecules -- water, hydrogen,
//!    the simple oxides and hydrides -- are always present, so a world always
//!    has a solvent and a few things to react.
//! 2. **Assembly.** Random valence-saturated molecules are built until the
//!    pool reaches a seed fraction of the target size.
//! 3. **Discovery.** Reactions are generated by graph rewrite, and any product
//!    not yet in the pool is *added* to it, until the pool is full. After that
//!    only reactions closing over existing compounds are accepted.
//!
//! Stage 3 is the important one. Growing the compound pool through the
//! reaction generator rather than independently of it means every compound
//! arrives attached to a reaction, so the network is connected by
//! construction. A pool filled independently would be mostly islands.

use std::collections::{BTreeMap, BTreeSet};

use hadean_core::rng::SeqRng;
use hadean_core::units::{kj_per_mol, AMU};

use crate::canon::{canonical_key, MoleculeKey};
use crate::chemistry::{
    band_energy, ChemParams, Chemistry, Compound, CompoundId, Drive, Reaction, ReactionId, KEY_DIM,
    N_BANDS,
};
use crate::element::{element, valence, ElementId, C, H, M, N, N_ELEMENTS, O, S, SKELETAL};
use crate::molecule::{Bond, Molecule, MAX_ATOMS};
use crate::rewrite::{merge, open_multiple, split_bond, Open};

/// Reference diffusion coefficient: water in water, m^2/s.
const D_REFERENCE: f32 = 2.3e-9;
/// Reference mass for scaling laws, amu (water).
const M_REFERENCE: f32 = 18.015;
/// Baseline membrane permeability for a small nonpolar molecule, m/s.
const P_REFERENCE: f32 = 5.0e-5;

/// Generate a chemistry from a seed.
pub fn generate(seed: u64, params: ChemParams) -> Chemistry {
    let mut rng = SeqRng::new(hadean_core::rng::mix64(seed ^ 0x0C0F_FEE0_C0DE_1111));
    let mut pool = Pool::new(params.n_compounds);

    for m in primordials() {
        pool.intern(m);
    }

    // Stage 2: assemble until a third of the pool is filled.
    let seed_target = (params.n_compounds / 3).max(pool.len());
    let mut attempts = 0;
    while pool.len() < seed_target && attempts < seed_target * 400 {
        attempts += 1;
        if let Some(m) = assemble(&mut rng, &params) {
            pool.intern(m);
        }
    }

    // Stage 3: discover reactions -- first growing the pool with their
    // products, then closing the network over the finished pool.
    let mut found = Found::default();
    grow(&mut rng, &mut pool, &params, &mut found);
    found.growth = found.list.len();
    close_network(&pool, &mut found);
    let reactions = energise(&mut rng, &pool, &params, found);

    // Derive per-compound properties now that the pool is final.
    let compounds: Vec<Compound> = pool
        .molecules
        .iter()
        .enumerate()
        .map(|(i, m)| derive_compound(i as CompoundId, m, &pool.names[i], pool.h_f[i], &params))
        .collect();

    let mut chem = Chemistry {
        water: find_water(&compounds),
        photo: Vec::new(),
        vent_fuel: rank_vent_fuel(&compounds),
        involving: index_reactions(&reactions, compounds.len()),
        compounds,
        reactions,
        params,
        seed,
    };
    designate_photochemistry(&mut chem, &mut rng);
    chem
}

/// The molecules every world contains regardless of seed.
fn primordials() -> Vec<Molecule> {
    let m = |atoms: Vec<ElementId>, bonds: Vec<(u8, u8, u8)>| {
        Molecule::new(
            atoms,
            bonds
                .into_iter()
                .map(|(a, b, o)| Bond::new(a, b, o))
                .collect(),
        )
    };
    vec![
        m(vec![H, H], vec![(0, 1, 1)]),                             // H2
        m(vec![O, O], vec![(0, 1, 2)]),                             // O2
        m(vec![N, N], vec![(0, 1, 3)]),                             // N2
        m(vec![O, H, H], vec![(0, 1, 1), (0, 2, 1)]),               // H2O
        m(vec![S, H, H], vec![(0, 1, 1), (0, 2, 1)]),               // H2S
        m(vec![C, O, O], vec![(0, 1, 2), (0, 2, 2)]),               // CO2
        m(vec![N, H, H, H], vec![(0, 1, 1), (0, 2, 1), (0, 3, 1)]), // NH3
        m(
            vec![C, H, H, H, H],
            vec![(0, 1, 1), (0, 2, 1), (0, 3, 1), (0, 4, 1)],
        ), // CH4
        m(vec![O, M, M], vec![(0, 1, 1), (0, 2, 1)]),               // M2O, a salt
    ]
}

/// A cut molecule: the two fragments plus their formulas.
///
/// Formulas are cached because reaction discovery rejects most candidates on
/// formula alone, and adding two six-element arrays is far cheaper than
/// building a product molecule and canonicalising it.
struct Split {
    left: Open,
    right: Open,
    fl: Formula,
    fr: Formula,
}

type Formula = [u16; N_ELEMENTS];

#[inline]
fn formula_sum(a: &Formula, b: &Formula) -> Formula {
    let mut out = *a;
    for i in 0..N_ELEMENTS {
        out[i] += b[i];
    }
    out
}

/// The interning table.
///
/// Caches everything expensive to recompute: formation enthalpies (which walk
/// the graph looking for rings), the set of formulas present, and the fragment
/// decomposition of every molecule.
///
/// A `BTreeMap` rather than a `HashMap` because we iterate it, and hash-map
/// order is randomised per process.
struct Pool {
    index: BTreeMap<MoleculeKey, CompoundId>,
    molecules: Vec<Molecule>,
    names: Vec<String>,
    h_f: Vec<f64>,
    formula: Vec<Formula>,
    /// Every splittable single bond, as a fragment pair.
    splits: Vec<Vec<Split>>,
    /// Every multiple bond, opened.
    opens: Vec<Vec<Open>>,
    present: BTreeSet<Formula>,
    formula_counts: BTreeMap<String, u32>,
    capacity: usize,
}

impl Pool {
    fn new(capacity: usize) -> Self {
        Self {
            index: BTreeMap::new(),
            molecules: Vec::new(),
            names: Vec::new(),
            h_f: Vec::new(),
            formula: Vec::new(),
            splits: Vec::new(),
            opens: Vec::new(),
            present: BTreeSet::new(),
            formula_counts: BTreeMap::new(),
            capacity,
        }
    }

    fn len(&self) -> usize {
        self.molecules.len()
    }

    fn is_full(&self) -> bool {
        self.len() >= self.capacity
    }

    /// Could a molecule with this formula be in the pool at all? The cheap
    /// pre-filter that makes exhaustive discovery affordable.
    #[inline]
    fn may_contain(&self, formula: &Formula) -> bool {
        self.present.contains(formula)
    }

    /// Look up an already-interned molecule without adding it.
    fn lookup(&self, m: &Molecule) -> Option<CompoundId> {
        self.index.get(&canonical_key(m)).copied()
    }

    /// Intern a molecule, adding it if the pool has room.
    /// Returns `None` only when the molecule is new and the pool is full.
    fn intern(&mut self, m: Molecule) -> Option<CompoundId> {
        if !m.is_valid() {
            return None;
        }
        let key = canonical_key(&m);
        if let Some(&id) = self.index.get(&key) {
            return Some(id);
        }
        if self.is_full() {
            return None;
        }
        let id = self.len() as CompoundId;
        let text = m.formula_string();
        let n = self.formula_counts.entry(text.clone()).or_insert(0);
        // Isomers share a formula, so disambiguate the second and later ones.
        let name = if *n == 0 {
            text
        } else {
            format!("{text}-{}", (b'a' + (*n as u8 - 1).min(24)) as char)
        };
        *n += 1;

        let splits = (0..m.bonds.len())
            .filter_map(|b| split_bond(&m, b))
            .map(|(left, right)| Split {
                fl: left.mol.formula(),
                fr: right.mol.formula(),
                left,
                right,
            })
            .collect();
        let opens = (0..m.bonds.len())
            .filter_map(|b| open_multiple(&m, b))
            .collect();

        self.index.insert(key, id);
        self.present.insert(m.formula());
        self.formula.push(m.formula());
        self.h_f.push(m.formation_enthalpy());
        self.splits.push(splits);
        self.opens.push(opens);
        self.molecules.push(m);
        self.names.push(name);
        Some(id)
    }
}

/// One side of a reaction: compound ids with coefficients, sorted.
type Side = Vec<(CompoundId, u8)>;

/// Group repeated compounds into `(id, coefficient)` pairs, sorted by id.
fn collate(ids: &[CompoundId]) -> Side {
    let mut out: Side = Vec::new();
    let mut sorted = ids.to_vec();
    sorted.sort_unstable();
    for id in sorted {
        match out.last_mut() {
            Some((last, n)) if *last == id => *n += 1,
            _ => out.push((id, 1)),
        }
    }
    out
}

fn enthalpy(pool: &Pool, side: &Side) -> f64 {
    side.iter()
        .map(|&(c, n)| pool.h_f[c as usize] * n as f64)
        .sum()
}

/// Accumulates reactions while rejecting duplicates and null rewrites.
#[derive(Default)]
struct Found {
    seen: BTreeSet<(Side, Side)>,
    list: Vec<(Side, Side)>,
    /// How many entries came from the growth phase. Those are the reactions
    /// that knit the compound pool together, so they survive truncation.
    growth: usize,
}

impl Found {
    fn add(&mut self, lhs: Side, rhs: Side) {
        if lhs == rhs {
            return; // the rewrite rebuilt its own reactants
        }
        // Reactions are reversible, so A->B and B->A are one reaction.
        if self.seen.contains(&(lhs.clone(), rhs.clone()))
            || self.seen.contains(&(rhs.clone(), lhs.clone()))
        {
            return;
        }
        self.seen.insert((lhs.clone(), rhs.clone()));
        self.list.push((lhs, rhs));
    }
}

/// Build one random valence-saturated molecule.
fn assemble(rng: &mut SeqRng, params: &ChemParams) -> Option<Molecule> {
    let n_core = 1 + rng.below(params.max_skeleton.max(1));
    let mut atoms: Vec<ElementId> = vec![*rng.pick(&SKELETAL)?];
    let mut bonds: Vec<Bond> = Vec::new();

    let free = |atoms: &[ElementId], bonds: &[Bond], i: u8| -> u8 {
        let used: u8 = bonds
            .iter()
            .filter_map(|b| b.other(i).map(|_| b.order))
            .sum();
        valence(atoms[i as usize]).saturating_sub(used)
    };

    for _ in 1..n_core {
        let e = *rng.pick(&SKELETAL)?;
        let hosts: Vec<u8> = (0..atoms.len() as u8)
            .filter(|&i| free(&atoms, &bonds, i) >= 1)
            .collect();
        let Some(&host) = rng.pick(&hosts) else { break };
        let cap = free(&atoms, &bonds, host).min(valence(e)).min(3);
        let order = pick_order(rng, cap);
        atoms.push(e);
        bonds.push(Bond::new(host, atoms.len() as u8 - 1, order));
    }

    // Occasionally close a ring, which is what gives the pool any structural
    // variety beyond trees.
    if atoms.len() >= 3 && rng.chance(0.18) {
        let open: Vec<u8> = (0..atoms.len() as u8)
            .filter(|&i| free(&atoms, &bonds, i) >= 1)
            .collect();
        if open.len() >= 2 {
            let i = *rng.pick(&open)?;
            let j = *rng.pick(&open)?;
            let already = bonds.iter().any(|b| b.other(i) == Some(j));
            if i != j && !already {
                bonds.push(Bond::new(i, j, 1));
            }
        }
    }

    // Saturate every remaining valence with a terminator.
    for i in 0..atoms.len() as u8 {
        while free(&atoms, &bonds, i) > 0 {
            if atoms.len() >= MAX_ATOMS {
                return None;
            }
            let term = if rng.chance(0.05) { M } else { H };
            atoms.push(term);
            bonds.push(Bond::new(i, atoms.len() as u8 - 1, 1));
        }
    }

    let mol = Molecule::new(atoms, bonds);
    mol.is_valid().then_some(mol)
}

/// Bond order, biased hard toward single bonds.
fn pick_order(rng: &mut SeqRng, cap: u8) -> u8 {
    let u = rng.unit();
    let wanted = if u < 0.68 {
        1
    } else if u < 0.93 {
        2
    } else {
        3
    };
    wanted.min(cap).max(1)
}

/// Stage 3a -- growth: random rewrites whose products are added to the pool.
///
/// Every compound therefore arrives attached to a reaction, so the network is
/// connected by construction. A pool filled independently of the reaction
/// generator would be mostly islands.
fn grow(rng: &mut SeqRng, pool: &mut Pool, params: &ChemParams, found: &mut Found) {
    let budget = params.n_compounds * 3_000;
    for _ in 0..budget {
        if pool.is_full() {
            return;
        }
        let a = rng.below(pool.len()) as CompoundId;
        let b = rng.below(pool.len()) as CompoundId;

        let products: Vec<Molecule> = if rng.chance(params.addition_fraction) {
            let Some(open_a) = pick(rng, &pool.opens[a as usize]) else {
                continue;
            };
            let Some(sb) = pick(rng, &pool.splits[b as usize]) else {
                continue;
            };
            let Some(half) = merge(open_a, 0, &sb.left, 0) else {
                continue;
            };
            let Some(c) = merge(&half, 0, &sb.right, 0).and_then(Open::close) else {
                continue;
            };
            vec![c]
        } else {
            let Some(sa) = pick(rng, &pool.splits[a as usize]) else {
                continue;
            };
            let Some(sb) = pick(rng, &pool.splits[b as usize]) else {
                continue;
            };
            let (p, q) = if rng.chance(0.5) {
                (&sb.left, &sb.right)
            } else {
                (&sb.right, &sb.left)
            };
            let Some(c) = merge(&sa.left, 0, p, 0).and_then(Open::close) else {
                continue;
            };
            let Some(d) = merge(&sa.right, 0, q, 0).and_then(Open::close) else {
                continue;
            };
            vec![c, d]
        };

        let mut ids = Vec::with_capacity(products.len());
        let mut ok = true;
        for m in products {
            match pool.intern(m) {
                Some(id) => ids.push(id),
                None => {
                    ok = false;
                    break;
                }
            }
        }
        if ok {
            found.add(collate(&[a, b]), collate(&ids));
        }
    }
}

/// Stage 3b -- closure: every reaction that closes over the finished pool.
///
/// This is exhaustive rather than sampled. Once the pool is full, a random
/// rewrite almost never lands back inside it, so sampling finds only a handful
/// of reactions no matter how large the budget. Enumerating instead is both
/// complete and cheaper, because a candidate is rejected on formula arithmetic
/// long before anything is built.
fn close_network(pool: &Pool, found: &mut Found) {
    let n = pool.len();

    // Exchange: cut one bond in each reactant, recombine the halves. The pair
    // is unordered -- swapping the roles of A and B gives the same products.
    for a in 0..n {
        for b in a..n {
            for sa in &pool.splits[a] {
                for sb in &pool.splits[b] {
                    for swap in [false, true] {
                        let (p, q, fp, fq) = if swap {
                            (&sb.left, &sb.right, &sb.fl, &sb.fr)
                        } else {
                            (&sb.right, &sb.left, &sb.fr, &sb.fl)
                        };
                        let f1 = formula_sum(&sa.fl, fp);
                        let f2 = formula_sum(&sa.fr, fq);
                        if !pool.may_contain(&f1) || !pool.may_contain(&f2) {
                            continue;
                        }
                        let Some(c) = merge(&sa.left, 0, p, 0).and_then(Open::close) else {
                            continue;
                        };
                        let Some(d) = merge(&sa.right, 0, q, 0).and_then(Open::close) else {
                            continue;
                        };
                        let (Some(ci), Some(di)) = (pool.lookup(&c), pool.lookup(&d)) else {
                            continue;
                        };
                        found.add(
                            collate(&[a as CompoundId, b as CompoundId]),
                            collate(&[ci, di]),
                        );
                    }
                }
            }
        }
    }

    // Addition: open a multiple bond in A, add the two halves of B across it.
    // Not symmetric in A and B, so both orders are enumerated. The product
    // formula does not depend on which bonds are chosen, so the pair can be
    // rejected before any bond is considered.
    for a in 0..n {
        if pool.opens[a].is_empty() {
            continue;
        }
        for b in 0..n {
            let f = formula_sum(&pool.formula[a], &pool.formula[b]);
            if !pool.may_contain(&f) {
                continue;
            }
            for open_a in &pool.opens[a] {
                for sb in &pool.splits[b] {
                    let Some(half) = merge(open_a, 0, &sb.left, 0) else {
                        continue;
                    };
                    let Some(c) = merge(&half, 0, &sb.right, 0).and_then(Open::close) else {
                        continue;
                    };
                    let Some(ci) = pool.lookup(&c) else { continue };
                    found.add(collate(&[a as CompoundId, b as CompoundId]), collate(&[ci]));
                }
            }
        }
    }

    // Isomerisation: any two compounds sharing a formula interconvert. These
    // are cheap to enumerate and matter more than their simplicity suggests --
    // they let a lineage restructure a molecule without changing what it is
    // made of, which is most of what intermediary metabolism does.
    for a in 0..n {
        for b in (a + 1)..n {
            if pool.formula[a] == pool.formula[b] {
                found.add(collate(&[a as CompoundId]), collate(&[b as CompoundId]));
            }
        }
    }
}

/// Turn discovered stoichiometries into reactions with energetics.
fn energise(rng: &mut SeqRng, pool: &Pool, params: &ChemParams, mut found: Found) -> Vec<Reaction> {
    // `n_reactions` is a cap, not a target: the network is however large the
    // chemistry supports. When it does bind, growth-phase reactions are kept
    // unconditionally -- they are what connects the compound pool -- and the
    // closure-phase remainder is sampled, so a truncated network still spans
    // the whole chemistry rather than its first corner in enumeration order.
    if found.list.len() > params.n_reactions {
        let keep = found.growth.min(params.n_reactions);
        let mut rest = found.list.split_off(keep);
        rng.shuffle(&mut rest);
        rest.truncate(params.n_reactions - keep);
        found.list.extend(rest);
    }

    let keys: Vec<[f32; KEY_DIM]> = pool.molecules.iter().map(structural_key).collect();

    found
        .list
        .into_iter()
        .enumerate()
        .map(|(i, (lhs, rhs))| {
            let dh = enthalpy(pool, &rhs) - enthalpy(pool, &lhs);
            let base = rng.range(params.ea_min_zj, params.ea_max_zj) as f64 * 1.0e-21;
            let ea_f = base + dh.max(0.0);
            let ea_r = ea_f - dh;
            let rate = rng.log_range(params.rate_min, params.rate_max);

            // A reaction's key is the mean of its participants' structural
            // keys, so chemically similar reactions sit close together and an
            // enzyme evolved for one has partial activity on its neighbours.
            let mut key = [0.0f32; KEY_DIM];
            let mut count = 0.0f32;
            for &(c, n) in lhs.iter().chain(rhs.iter()) {
                for k in 0..KEY_DIM {
                    key[k] += keys[c as usize][k] * n as f32;
                }
                count += n as f32;
            }
            for k in &mut key {
                *k /= count.max(1.0);
            }

            Reaction {
                id: i as ReactionId,
                reactants: lhs,
                products: rhs,
                dh,
                ea_f,
                ea_r,
                rate,
                drive: Drive::Thermal,
                key,
            }
        })
        .collect()
}

/// Pick one element, or `None` if empty.
fn pick<'a, T>(rng: &mut SeqRng, xs: &'a [T]) -> Option<&'a T> {
    if xs.is_empty() {
        None
    } else {
        Some(&xs[rng.below(xs.len())])
    }
}

/// Structural descriptor, the basis of every affinity key in the simulation.
fn structural_key(m: &Molecule) -> [f32; KEY_DIM] {
    let n = m.n_atoms() as f32;
    let mass_amu = m.mass() as f64 / AMU;
    let hetero = m.atoms.iter().filter(|&&e| e != H && e != C).count() as f32;
    [
        (n / 6.0).tanh(),
        ((mass_amu / 60.0) as f32).tanh(),
        m.polarity(),
        m.charge() as f32 / 2.0,
        m.ring_count() as f32,
        m.conjugation() as f32 / 3.0,
        ((m.formation_enthalpy() / m.n_atoms() as f64) / 1.0e-19) as f32,
        hetero / n,
    ]
}

/// Compute everything the simulation needs to know about one compound.
fn derive_compound(
    id: CompoundId,
    m: &Molecule,
    name: &str,
    h_f: f64,
    params: &ChemParams,
) -> Compound {
    let mass = m.mass();
    let mass_amu = mass as f64 / AMU;
    let polarity = m.polarity();
    let charge = m.charge();

    // Stokes-Einstein: D scales with 1/radius, and radius with mass^(1/3).
    let diffusion = D_REFERENCE * (M_REFERENCE / mass_amu as f32).cbrt();

    // A lipid bilayer passes small nonpolar molecules and blocks polar or
    // charged ones. Used from L4; precomputed here so the cell layer never
    // has to think about molecular structure.
    let permeability = P_REFERENCE
        * (M_REFERENCE / mass_amu as f32).sqrt()
        * (-6.0 * polarity).exp()
        * if charge == 0 { 1.0 } else { 1.0e-3 };

    let (absorption, emission) = spectra(m, params);

    Compound {
        id,
        name: name.to_string(),
        formula: m.formula(),
        mass,
        h_f,
        diffusion,
        permeability,
        absorption,
        emission,
        charge,
        polarity,
        key: structural_key(m),
        molecule: m.clone(),
    }
}

/// Absorption and emission spectra.
///
/// Conjugated systems absorb at lower photon energies -- the more delocalised
/// the electrons, the redder the absorption. Saturated molecules are nearly
/// transparent. This is why an evolved pigment shows up as a colour in the
/// viewer without any special-casing: the same eight numbers drive the light
/// field and the render.
fn spectra(m: &Molecule, params: &ChemParams) -> ([f32; N_BANDS], [f32; N_BANDS]) {
    let conj = m.conjugation();
    let multiple = m.bonds.iter().filter(|b| b.order >= 2).count();
    let hetero_multiple = m
        .bonds
        .iter()
        .filter(|b| b.order >= 2 && m.atoms[b.a as usize] != m.atoms[b.b as usize])
        .count();

    let mut absorption = [0.0f32; N_BANDS];
    let mut emission = [0.0f32; N_BANDS];

    // A saturated molecule is left exactly transparent rather than given a
    // small uniform floor. A floor would be indistinguishable from the
    // medium's own extinction anyway, and it would make every compound count
    // as a pigment -- which turns the light solver's inner loop from "the
    // handful of species that matter" into "all of them".
    if multiple == 0 {
        return (absorption, emission);
    }

    // More conjugation -> lower transition energy -> redder peak (lower band).
    let peak = (N_BANDS as f32 - 1.0) - 1.9 * conj as f32 - 0.8 * hetero_multiple as f32;
    let peak = peak.clamp(0.0, N_BANDS as f32 - 1.0);
    let width = 1.15f32;
    let strength = 3.0e-24 * (1.0 + 1.6 * conj as f32) * multiple as f32 * params.absorption_scale;

    for (b, a) in absorption.iter_mut().enumerate() {
        let d = (b as f32 - peak) / width;
        *a += strength * (-0.5 * d * d).exp();
    }

    // Strongly conjugated species fluoresce, one band to the red of the peak.
    if conj >= 2 {
        let e_band = (peak - 1.0).clamp(0.0, N_BANDS as f32 - 1.0) as usize;
        emission[e_band] = 0.15 * conj as f32;
    }

    (absorption, emission)
}

fn find_water(compounds: &[Compound]) -> CompoundId {
    compounds
        .iter()
        .find(|c| c.name == "H2O")
        .map(|c| c.id)
        .expect("water is a primordial and is always interned")
}

/// Rank compounds by how much energy they carry per atom. The most weakly
/// bound small molecules are the ones vents inject as fuel.
fn rank_vent_fuel(compounds: &[Compound]) -> Vec<CompoundId> {
    let mut candidates: Vec<&Compound> = compounds.iter().filter(|c| c.n_atoms() <= 6).collect();
    candidates.sort_by(|a, b| {
        b.enthalpy_per_atom()
            .partial_cmp(&a.enthalpy_per_atom())
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| a.id.cmp(&b.id))
    });
    candidates.into_iter().take(6).map(|c| c.id).collect()
}

fn index_reactions(reactions: &[Reaction], n_compounds: usize) -> Vec<Vec<ReactionId>> {
    let mut index = vec![Vec::new(); n_compounds];
    for r in reactions {
        for &(c, _) in r.reactants.iter().chain(r.products.iter()) {
            let v = &mut index[c as usize];
            if !v.contains(&r.id) {
                v.push(r.id);
            }
        }
    }
    index
}

/// Choose which reactions light drives.
///
/// A photochemical reaction must be uphill (it stores energy), must be within
/// reach of a single photon, and must involve a compound that actually absorbs
/// in that band. These are the reactions that make the surface a resource-rich
/// place and give the world its vertical gradient.
fn designate_photochemistry(chem: &mut Chemistry, rng: &mut SeqRng) {
    let mut candidates: Vec<(ReactionId, u8, f32)> = Vec::new();

    for r in &chem.reactions {
        if r.dh <= 0.0 {
            continue;
        }
        for band in 0..N_BANDS {
            if r.dh > band_energy(band) {
                continue;
            }
            // How strongly do this reaction's participants absorb here?
            let absorb: f32 = r
                .reactants
                .iter()
                .chain(r.products.iter())
                .map(|&(c, _)| chem.compound(c).absorption[band])
                .fold(0.0, f32::max);
            candidates.push((r.id, band as u8, absorb));
        }
    }

    candidates.sort_by(|a, b| {
        b.2.partial_cmp(&a.2)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| a.0.cmp(&b.0))
    });

    let mut chosen: Vec<ReactionId> = Vec::new();
    for (id, band, _) in candidates {
        if chosen.len() >= chem.params.n_photo {
            break;
        }
        if chosen.contains(&id) {
            continue;
        }
        chosen.push(id);
        chem.reactions[id as usize].drive = Drive::Photo { band };
        // Photochemistry bypasses the thermal barrier, so give it a modest
        // spread of intrinsic rates rather than reusing the thermal one.
        chem.reactions[id as usize].rate = rng.log_range(1.0, 20.0);
    }
    chosen.sort_unstable();
    chem.photo = chosen;
}

/// Element counts as a formula string, for diagnostics.
pub fn formula_of(f: &[u16; N_ELEMENTS]) -> String {
    let mut s = String::new();
    for (e, &n) in f.iter().enumerate() {
        if n > 0 {
            s.push_str(element(e as ElementId).symbol);
            if n > 1 {
                s.push_str(&n.to_string());
            }
        }
    }
    s
}

/// Convenience: kJ/mol formatting for logs.
pub fn kj(x: f64) -> f64 {
    x / kj_per_mol(1.0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::chemistry::Drive;

    fn chem(seed: u64) -> Chemistry {
        generate(seed, ChemParams::default())
    }

    #[test]
    fn reachability_answers_what_a_pond_could_ever_hold() {
        // The primordial soup, closed over the reaction network. Every
        // primordial is trivially reachable, the closure only grows, and it
        // is a strict subset of a closure seeded with more.
        let chem = chem(4);
        let soup: Vec<u16> = ["H2O", "H2", "O2", "N2", "H2S", "CO2", "H3N", "CH4", "OM2"]
            .iter()
            .filter_map(|n| chem.by_name(n))
            .collect();
        assert!(soup.len() >= 8, "the primordials went missing");

        let from_soup = chem.reachable_from(&soup);
        for &c in &soup {
            assert!(from_soup[c as usize], "a seed compound was not reachable");
        }

        let mut with_vents = soup.clone();
        with_vents.extend_from_slice(&chem.vent_fuel);
        let from_vents = chem.reachable_from(&with_vents);
        for (c, &reachable) in from_soup.iter().enumerate() {
            assert!(
                !reachable || from_vents[c],
                "adding vent fuel made {} unreachable",
                chem.compound(c as u16).name
            );
        }

        // Nothing at all reaches nothing at all.
        assert!(chem.reachable_from(&[]).iter().all(|&r| !r));

        // Reachability is necessary, not sufficient: seed 4's pond reaches
        // far more compounds than it ever accumulates, which is exactly why
        // the ancestor's metabolism is chosen from measurement instead.
        let reachable = from_vents.iter().filter(|&&r| r).count();
        assert!(reachable > soup.len(), "the network reaches nothing new");
    }

    #[test]
    fn generation_is_deterministic() {
        use hadean_core::hash::HashState;
        let a = chem(12345);
        let b = chem(12345);
        assert_eq!(a.state_hash(), b.state_hash());
        assert_eq!(a.compounds.len(), b.compounds.len());
        assert_eq!(a.reactions.len(), b.reactions.len());
    }

    #[test]
    fn different_seeds_give_different_chemistries() {
        use hadean_core::hash::HashState;
        assert_ne!(chem(1).state_hash(), chem(2).state_hash());
    }

    #[test]
    fn every_generated_chemistry_verifies() {
        for seed in 0..24u64 {
            let c = chem(seed);
            c.verify().unwrap_or_else(|e| panic!("seed {seed}: {e}"));
        }
    }

    #[test]
    fn primordials_are_always_present() {
        for seed in 0..8u64 {
            let c = chem(seed);
            // Names are Hill notation, so ammonia reads H3N rather than NH3.
            for name in ["H2O", "H2", "O2", "N2", "CO2", "CH4", "H3N", "H2S"] {
                assert!(c.by_name(name).is_some(), "seed {seed} is missing {name}");
            }
        }
    }

    #[test]
    fn the_pool_fills_and_the_network_is_connected() {
        for seed in 0..8u64 {
            let c = chem(seed);
            assert_eq!(c.n_compounds(), c.params.n_compounds, "seed {seed}");
            // The closed network is as large as the chemistry supports, not
            // as large as the cap. At 32 compounds that is typically 60-150.
            assert!(
                c.n_reactions() > 40,
                "seed {seed}: {} reactions",
                c.n_reactions()
            );
            // Growing the pool through the reaction generator should leave
            // almost nothing isolated.
            let reactive = c.reactive_compounds();
            assert!(
                reactive * 10 >= c.n_compounds() * 9,
                "seed {seed}: only {reactive}/{} compounds react",
                c.n_compounds()
            );
        }
    }

    #[test]
    fn barriers_respect_detailed_balance() {
        let c = chem(7);
        for r in &c.reactions {
            assert!(r.ea_f >= 0.0 && r.ea_r >= 0.0);
            assert!(r.ea_f >= r.dh.max(0.0) - 1e-30, "forward barrier below dh");
            assert!((r.ea_f - r.ea_r - r.dh).abs() < 1e-28);
        }
    }

    #[test]
    fn photochemistry_is_uphill_and_photon_limited() {
        let c = chem(3);
        assert!(!c.photo.is_empty(), "no photochemistry designated");
        for &id in &c.photo {
            let r = c.reaction(id);
            let Drive::Photo { band } = r.drive else {
                panic!("reaction {id} is in photo but not photo-driven");
            };
            assert!(r.dh > 0.0, "photochemistry must store energy");
            assert!(
                r.dh <= band_energy(band as usize),
                "one photon must suffice"
            );
        }
    }

    #[test]
    fn vent_fuel_is_energetic_and_small() {
        let c = chem(5);
        assert!(!c.vent_fuel.is_empty());
        let fuel = c.compound(c.vent_fuel[0]);
        assert!(fuel.n_atoms() <= 6);
        // Vent fuel must be less stable per atom than the world's mean.
        let mean: f64 = c
            .compounds
            .iter()
            .map(|x| x.enthalpy_per_atom())
            .sum::<f64>()
            / c.n_compounds() as f64;
        assert!(fuel.enthalpy_per_atom() > mean);
    }

    #[test]
    fn compound_properties_are_physical() {
        let c = chem(11);
        for x in &c.compounds {
            assert!(x.diffusion > 0.0 && x.diffusion < 1.0e-7, "{}: D", x.name);
            assert!(x.permeability >= 0.0, "{}: P", x.name);
            assert!(x.mass > 0.0);
            assert!(x.h_f < 0.0, "{} should be bound", x.name);
            assert!(x.absorption.iter().all(|a| a.is_finite() && *a >= 0.0));
        }
        // Water must be far less membrane-permeable than methane.
        let w = c.compound(c.water);
        let ch4 = c.compound(c.by_name("CH4").unwrap());
        assert!(ch4.permeability > w.permeability * 5.0);
    }

    #[test]
    fn most_reactions_are_barred_at_ambient_temperature() {
        // The whole point of a cell is to make favourable reactions actually
        // happen. If most reactions ran on their own there would be nothing
        // for an enzyme to do.
        let c = chem(13);
        let ambient = hadean_core::units::T_AMBIENT;
        let fast = c
            .reactions
            .iter()
            .filter(|r| r.k_forward(ambient, 0.0) > 1.0e-3)
            .count();
        let frac = fast as f32 / c.n_reactions() as f32;
        assert!(
            frac < 0.5,
            "{:.0}% of reactions run uncatalysed",
            frac * 100.0
        );
        assert!(
            frac > 0.0,
            "no reaction runs at all; the world would be inert"
        );
    }
}
