//! **L1 -- Chemistry.** Elements, molecules, a procedurally generated reaction
//! network, and the kinetics that run it.
//!
//! This is the foundation the rest of the simulation stands on. Metabolism,
//! food webs, and decomposition are not separate systems: they are what a
//! reaction network looks like when cells are using it.
//!
//! Two properties make the chemistry safe to build life on:
//!
//! * **Mass balance is structural.** Reactions are generated by cutting and
//!   rejoining atom graphs ([`rewrite`]), so an unbalanced reaction cannot be
//!   expressed, let alone generated.
//! * **Free energy is impossible to manufacture.** A compound's enthalpy is a
//!   function of its structure alone, so every reaction's `dh` is a difference
//!   of potentials and any cycle of reactions sums to exactly zero. Organisms
//!   cannot evolve into perpetual motion machines, which is the failure mode
//!   that ends simulations like this one.
//!
//! Everything here is a pure function of `(seed, ChemParams)`.

pub mod canon;
pub mod chemistry;
pub mod element;
pub mod generate;
pub mod kinetics;
pub mod molecule;
pub mod rewrite;

pub use chemistry::*;
pub use generate::generate;
pub use kinetics::{Network, VoxelStep};
pub use molecule::{Bond, Molecule};
